Rework undockerify command.

diff --git a/bin/undockerify b/bin/undockerify
--- a/bin/undockerify
+++ b/bin/undockerify
@@ -11,7 +11,42 @@ export PI_INCLUDE="${PDIR}/inc"
 NAME="${1-pi:build}"
 shift
 
-echo "Creating Raspberry Pi image ${PI_IMAGE_FILE} from docker container ${NAME}"
+echo "Creating Raspberry Pi image ${PI_IMAGE_FILE} from docker image ${NAME}"
 echo "This will take some time."
 
-docker export "${NAME}" - | rpi-image-tool create-image "${@}" || error "Image load failed"
+SCRIPTFILE="/tmp/$$.$RANDOM.script"
+
+cat >"${SCRIPTFILE}" <<'EOF'
+#!/bin/bash
+# Directories to not export
+EXCLUDE=(
+    "dev/*"
+    "proc/*"
+    "sys/*"
+    "tmp/*"
+    "run/*"
+    "mnt/*"
+    "media/*"
+    "var/run"
+    "var/lock"
+    "var/spool"
+    "var/cache/ldconfig/*"
+    "var/cache/debconf/*"
+    "var/cache/fontconfig/*"
+    "var/cache/private/*"
+    "var/cache/man/*"
+    "lost+found"
+    "etc/fstab"
+    "/undockerify"
+    )
+EXCLUDES=()
+for E in "${EXCLUDE[@]}"; do
+    EXCLUDES+=(--exclude "${E}")
+done
+
+# Dump the relevant parts of the filesystem to a tar file.
+tar --create --file "-" "${EXCLUDES[@]}" -C / --checkpoint=5000 --checkpoint-action='echo=%u %T%*\r' .
+EOF
+chmod a+x "${SCRIPTFILE}"
+
+docker run -rm -v "${SCRIPTFILE}:/undockerify" "${NAME}"  /undockerify | rpi-image-tool create-image "${@}" || error "Image load failed"
